# Generated by Django 4.1.7 on 2023-02-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('task_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
