# Generated by Django 4.1.7 on 2023-02-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_taskstate_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='missing', max_length=100)),
                ('ip', models.CharField(default='missing', max_length=45)),
                ('timestamp', models.CharField(default='missing', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='TaskState',
        ),
    ]
